# inherit_from: .rubocop_todo.yml

# require:
#   - rubocop-rails

# Rails:
#   Enabled: true

# AllCops:
#   Exclude:
#     - "vendor/**/*"
#     - "bin/**"
#     - "db/schema.rb"
#     - "node_modules/**/*"
#     - "tmp/**/*"
#     - "lib/**/*"


# AsciiComments:
#   Enabled: false

# Style/BlockDelimiters:
#   AutoCorrect: false